### ISSUE TITLE
feature request:  top of hour

### ISSUE THREAD

**Issue by tricker** [Gabb1995/insomnia-plugin-customtimestamp#2]
This project is cool.   Albeit esoteric, I have the use case of need to calculate X hours out but the top of the hour (eg. `2021-04-02T16:00:00.000Z`.  Whether it rounds up or down is unimportant.

**Comment by Gabb1995** [comment]
You can just do `YYYY-MM-DDTHH:00:00.000\Z` in custom format

**Comment by Gabb1995** [comment]
![Screenshot from 2021-10-08 11:48:17](https://user-images.githubusercontent.com/20728259/136535739-77ed1898-2ded-4690-bc32-9de44c5c1f13.png)
